[workspace]
members = [
    "crates/freja-audit",
    "crates/freja",
    "crates/freja-config",
    "crates/freja-domain",
    "crates/freja-policy",
    "crates/freja-proxy",
    "crates/freja-ui",
]
default-members = ["crates/freja"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["karanabe"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/karanabe/freja"
readme = "README.md"
rust-version = "1.88"
publish = ["crates-io"]

[workspace.dependencies]
arc-swap = "1.7.1"
async-trait = "0.1.89"
base64 = "0.22.1"
bytes = "1.11.1"
clap = { version = "4.5.46", features = ["derive"] }
ed25519-dalek = "2.2.0"
freja-audit = { version = "0.1.0", path = "crates/freja-audit" }
freja-config = { version = "0.1.0", path = "crates/freja-config" }
freja-domain = { version = "0.1.0", path = "crates/freja-domain" }
freja-policy = { version = "0.1.0", path = "crates/freja-policy" }
freja-proxy = { version = "0.1.0", path = "crates/freja-proxy" }
freja-ui = { version = "0.1.0", path = "crates/freja-ui" }
hex = "0.4.3"
http = "1.3.1"
http-body-util = "0.1.3"
hyper = { version = "1.7.0", features = ["client", "http1", "http2", "server"] }
hyper-util = { version = "0.1.16", features = ["client-legacy", "http1", "server", "tokio"] }
ipnet = { version = "2.11.0", features = ["serde"] }
pingora-core = "=0.8.1"
ratatui = "=0.30.2"
rcgen = { version = "0.14.9", features = ["x509-parser"] }
rustls = { version = "0.23.35", default-features = false, features = ["ring", "std", "tls12"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
sha2 = "0.10.9"
tokio = { version = "1.47.1", features = ["full"] }
tokio-rustls = { version = "0.26.4", default-features = false, features = ["ring", "tls12"] }
toml = "0.9.5"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter", "fmt"] }
url = "2.5.7"
uuid = { version = "1.18.0", features = ["serde", "v4"] }
webpki-roots = "1.0.3"

[workspace.lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
module_name_repetitions = "allow"
must_use_candidate = "allow"
